# Generated by Django 5.2.8 on 2026-02-01 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0003_apartment_name_alter_apartment_apartments_images_and_more'),
        ('subleases', '0003_sublease_name_alter_sublease_apartments_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_apartments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
                ('favorites_sublease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subleases.sublease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
