# Generated by Django 5.2.8 on 2026-02-27 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_name_alter_apartment_apartments_images_and_more'),
        ('subleases', '0003_sublease_name_alter_sublease_apartments_images_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_favorites', to='apartments.apartment')),
                ('sublease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublease_favorites', to='subleases.sublease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'apartment'), name='unique_user_apartment_favorite'), models.UniqueConstraint(fields=('user', 'sublease'), name='unique_user_sublease_favorite')],
            },
        ),
    ]
