# Generated by Django 5.2.8 on 2026-02-01 22:01

import apartments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_leasingcompany_apartment_leasingcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartments_images',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apartments.models.timestamped_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
            ],
        ),
    ]
