# Generated by Django 5.2.8 on 2026-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_name_alter_apartment_apartments_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sqft_living',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
