# Generated by Django 5.2.8 on 2026-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartment_bedrooms_alter_apartment_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='price',
            new_name='prices',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sqft_living',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
