# Generated by Django 6.0.1 on 2026-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_rename_price_apartment_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
