# Generated by Django 5.2.8 on 2026-04-17 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_airequestlog_favoriteactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airequestlog',
            name='normalized_request',
        ),
        migrations.RemoveField(
            model_name='airequestlog',
            name='normalized_response',
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='prompt_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='thinking_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='total_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='mode',
            field=models.CharField(choices=[('local', 'Local RAG'), ('api', 'API')], db_index=True, default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteactionlog',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='favoriteactionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
