# Generated by Django 5.2.8 on 2026-02-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subleases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sublease',
            name='social_media_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subleases.socialmediasite'),
        ),
    ]
