# Generated by Django 5.2.8 on 2026-02-01 22:01

import django.db.models.deletion
import subleases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subleases', '0002_socialmediasite_sublease_social_media_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublease',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sublease',
            name='apartments_images',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubleaseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=subleases.models.timestamped_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sublease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='subleases.sublease')),
            ],
        ),
    ]
