# Generated by Django 5.2.8 on 2026-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subleases', '0003_sublease_name_alter_sublease_apartments_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublease',
            name='prices',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sublease',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
